### ISSUE TITLE
Default State "queueing" 

### ISSUE THREAD

**Issue by HowardWhile** [drmibell/node-red-contrib-queue-gate#1]
Hi drmibell.

I meet some problem when set Default State to queueing.

After deploy each time. The node can not queue any msg. 

`[{"id":"355438e0.4f00d8","type":"inject","z":"b3781170.1b0e6","name":"input","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":450,"y":580,"wires":[["4e581095.d5707"]]},{"id":"259f7314.fb41bc","type":"debug","z":"b3781170.1b0e6","name":"output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":770,"y":580,"wires":[]},{"id":"4e581095.d5707","type":"q-gate","z":"b3781170.1b0e6","name":"","controlTopic":"control","defaultState":"queueing","openCmd":"open","closeCmd":"close","toggleCmd":"toggle","queueCmd":"queue","defaultCmd":"default","triggerCmd":"trigger","flushCmd":"flush","purgeCmd":"purge","maxQueueLength":"100","x":610,"y":580,"wires":[["259f7314.fb41bc"]]},{"id":"4766f179.c68be","type":"inject","z":"b3781170.1b0e6","name":"flush","topic":"control","payload":"flush","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":450,"y":620,"wires":[["4e581095.d5707"]]}]`

Now, I am need to inject once Queuing type Control Topic msg. 

Let it recover and work on "queueing" state.

`[{"id":"355438e0.4f00d8","type":"inject","z":"b3781170.1b0e6","name":"input","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":450,"y":580,"wires":[["4e581095.d5707"]]},{"id":"259f7314.fb41bc","type":"debug","z":"b3781170.1b0e6","name":"output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":770,"y":580,"wires":[]},{"id":"4e581095.d5707","type":"q-gate","z":"b3781170.1b0e6","name":"","controlTopic":"control","defaultState":"queueing","openCmd":"open","closeCmd":"close","toggleCmd":"toggle","queueCmd":"queue","defaultCmd":"default","triggerCmd":"trigger","flushCmd":"flush","purgeCmd":"purge","maxQueueLength":"100","x":610,"y":580,"wires":[["259f7314.fb41bc"]]},{"id":"f399e103.2faec","type":"inject","z":"b3781170.1b0e6","name":"queue","topic":"control","payload":"queue","payloadType":"str","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":450,"y":540,"wires":[["4e581095.d5707"]]},{"id":"4766f179.c68be","type":"inject","z":"b3781170.1b0e6","name":"flush","topic":"control","payload":"flush","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":450,"y":620,"wires":[["4e581095.d5707"]]}]`

I hope you have time to make it better.
 
This is my usage environment description
```shell
20 Oct 15:03:08 - [info] Node-RED version: v0.19.4
20 Oct 15:03:08 - [info] Node.js  version: v6.14.4
20 Oct 15:03:08 - [info] Linux 4.15.0-15-generic x64 LE
```

**Comment by drmibell** [comment]
Definitely a bug, but not an obvious one. I'll post a fix as soon as I find one.

**Comment by drmibell** [comment]
Pushed v0.0.3 to GitHub with bug fix. Please test from there, if possible. Otherwise, I will upload to npm

**Comment by drmibell** [comment]
Version 0.0.3 tested and pushed to npm.
