### ISSUE TITLE
Feature Request - Open/process automatically when queues below 1

### ISSUE THREAD

**Issue by davismm85** [drmibell/node-red-contrib-queue-gate#12]
Hello, I am very new to this and I would like to thank you in advance for developing q-gate.

I am unsure if I am just missing something or if the feature does not exist. What I am trying to do is using the q-gate to queue up messages coming in from a chatbot.

Node Red receives a payload through my ChatBot. From there, I have q-gate queuing up the messages. The ChatBat will trigger a flow and then I send a payload trigger function to start my next queued message.

The issue I am running into is the initial start. Since I am going from ChatBot --> to a queued state q-gate, the messages just stay in queue. Somehow I would like q-gate to automatically process going from 0 to 1 messages in queue. This should kick off all my flows and get it back to 0 waiting for the next message.

If more details are needed let me know. Thanks again, Matt

**Comment by colinl** [comment]
Why are you queueing the messages?

**Comment by davismm85** [comment]
Sorry for the delay, I am queuing Chat messages from a Twitch Chat I have. I don't want users to send command !x, !y, !z and they all go off at the same time. I want X to finish, then Y, then Z. I did figure this out with another queue node from node-red so this is no longer needed.

I appreciate the reply
