### ISSUE TITLE
[Feature Request] Possibility to chose which context store

### ISSUE THREAD

**Issue by Steve-Mcl** [drmibell/node-red-contrib-queue-gate#13]
Hi Michael, I am reviewing your node as a possible replacement for a subflow I wrote that has most of these features (peek, shift, clear etc) and uses persistent context.  It used to ensure database writes are done before de-queuing.  For me, the most important part is retaining data between node-red restarts.

Typically, in node-red, we have 2 context stores, memory only and a file based store & the default is always "memory only" and I cant change that.  That means your node doesnt persist the queue for my situation. If your node permitted a choice of which context store is used, that would overcome this problem.

Thanks for the consideration.

**Comment by drmibell** [comment]
Hi Steve, sorry for the slow response. That's a good suggestion and probably not terribly difficult to implement. There has been some relevant discussion on the forum, and I will check it out when I get a chance. (It may be a few days, since I'm pretty busy at the moment.) I'll let you know when I have something you can test or if I run into any serious issues.

**Comment by Steve-Mcl** [comment]
Good stuff. Thanks for the consideration. 

I am pretty sure there is a way to enumerate the available stores so might be a fairly simple modification.

**Comment by drmibell** [comment]
I have pushed a new branch called `select_contextStore` that allows the user to choose among the stores available. It has rough edges and was a bit of a challenge, since I have never used jQuery.  Sorry for the delay -- life happens, and I often wish I could run with interrupts disabled. Please send feedback.

**Comment by Steve-Mcl** [comment]
Hi ya. Sorry I've just noticed this comment. I'll give it a go as soon as I can and feed back.

**Comment by drmibell** [comment]
I have pushed an update of the `select_contextStore` branch that I hope will fix things. I need to do more testing and documentation, but I'd be grateful if you could take a look at it.

**Comment by drmibell** [comment]
@Steve-Mcl, I have the documentation ready to roll out, and I'm fairly confident that everything works. Have you had a chance to do any testing?

**Comment by Steve-Mcl** [comment]
@drmibell hi my apologies - super busy.  Just cloned this repo and set the branch to `select_contextStore` and installing right now.

**Comment by drmibell** [comment]
Thanks. No apologies needed.

**Comment by Steve-Mcl** [comment]
Hi Michael, my tests show state is restored on reboot or node-red when file context is selected 👍 

Some suggestions (nit picking TBH)...

1. Perhaps the drop down should be disabled or hidden when not persisting...
![SNL1VHQmQY](https://user-images.githubusercontent.com/44235289/98289655-6aaec880-1fa0-11eb-92b9-f51b9c039c06.gif)

```
$("#node-input-persist").on("change", function(e) { $("#node-input-storeName").prop("disabled", !$(this).prop("checked")) } );
```

2. Also maybe consider, in oneditprepare, select the first item in the list if non is set?

Otherwise, spot on.

**Comment by drmibell** [comment]
Thanks for the  👍. Your suggestions were in the plan but missed on execution -- mostly thanks to the jQuery skills mentioned above. I will probably publish as is, but I plan to add this feature to `node-red-contrib-simple-gate` and can chase the nits then for both nodes. I appreciate your suggestions and help. Hope you find the node useful.

**Comment by drmibell** [comment]
Steve, since we are about closing issues, is there anything else you would like to see done here?
