### ISSUE TITLE
I am not understanding why I am seeing this error.

### ISSUE THREAD

**Issue by Just-another-pleb** [drmibell/node-red-contrib-queue-gate#17]
Hi.

I use your node and have recently gone around and got rid of other nodes similar.
Partly because I also use your `gate` node.

Anyway, this is a weird one:

Note:   **msg.payload.toLowerCase is not a function** and the `source`  "source":{"id":"7bc998b7.b8c538"  which is your node.

```
{"message":"TypeError: msg.payload.toLowerCase is not a function","source":{"id":"7bc998b7.b8c538","type":"q-gate","name":"qgate","count":1},"stack":"TypeError: msg.payload.toLowerCase is not a function\n    at QueueGateNode._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-queue-gate/q-gate.js:79:37)\n    at hooks.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26)\n    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/hooks.js:113:9)\n    at QueueGateNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)\n    at QueueGateNode.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)\n    at QueueGateNode.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)\n    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:657:52)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"}
```

This is a screen shot of where it is in the scheme of things:

![Screenshot from 2021-01-13 11-42-01](https://user-images.githubusercontent.com/39888280/104391791-c98e5080-5594-11eb-86e5-5f880d6bb87b.png)

Ok, it gets its *input* from the `link` node.
No problem.
Only 2 places.

![Screenshot from 2021-01-13 11-46-09](https://user-images.githubusercontent.com/39888280/104391997-3bff3080-5595-11eb-8e5e-8fab8acc3fe4.png)
![Screenshot from 2021-01-13 11-46-32](https://user-images.githubusercontent.com/39888280/104391998-3dc8f400-5595-11eb-8cd4-13054ef653e4.png)

As you may see, I have added stuff on both of those to catch from where this "convert to lowercase" is coming.

Neither of those nodes - when they have messages - have anything like that.
They have the expected messages.

So I am asking if you could do a sanity check and I am not going mad.
Thanks.

**Comment by drmibell** [comment]
I'm almost certain that you are sane. A few things could help me find your problem. Most important would be to see the complete message going into the `q-gate` node that triggers the error. I suspect that the message is unusual in some way that is not handled properly by the node. It might also help to get a copy of your flow, or better yet, a simplified version that gives the same error. (Your flow looks complicated, and your palette has lots of sub flows, so I might not be able to run it without some simplification.) The good news is that there is really only one place in the code that can produce that error, and it should not be hard to sort things out.

**Comment by drmibell** [comment]
On second thought, are you running a version of `q-gate` older than 1.4.0? The message you are getting looks to be one that should not be produced by a newer version. If your version is old, please update and see whether you still get the error.

**Comment by Just-another-pleb** [comment]
This is the complete error which NR captures:

```
{"message":"TypeError: msg.payload.toLowerCase is not a function","source":{"id":"93d25089.579ef8","type":"q-gate","name":"qgate","count":1},"stack":"TypeError: msg.payload.toLowerCase is not a function\n    at QueueGateNode._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-queue-gate/q-gate.js:79:37)\n    at hooks.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26)\n    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/hooks.js:113:9)\n    at QueueGateNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)\n    at QueueGateNode.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)\n    at QueueGateNode.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)\n    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:657:52)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)"}
```

Version:  1.3.0

I'll hold off a few minutes on the update. in case you have something to say.

Oh and I see it is now 1.5.2 available.

**Comment by drmibell** [comment]
Please do the upgrade. It will almost certainly eliminate the error message. Since there is something odd about the message you are feeding into the node, you still might not get the behavior you want, but we can deal with that.

**Comment by Just-another-pleb** [comment]
It seems to happen at/on reboot.

A new *fresh cut* of the error:

```
TypeError: msg.payload.toLowerCase is not a function    at QueueGateNode._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-queue-gate/q-gate.js:79:37)    at hooks.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26)    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/hooks.js:113:9)    at QueueGateNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)    at QueueGateNode.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)    at QueueGateNode.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:657:52)    at runCallback (timers.js:705:18)    at tryOnImmediate (timers.js:676:5)    at processImmediate (timers.js:658:5)
```

3 ittarations of it.  (Won't post the others)

I looked at the other two points which feed into there.

This is what I see/saw:

![Screenshot from 2021-01-13 15-21-58](https://user-images.githubusercontent.com/39888280/104406488-85f70f00-55b3-11eb-9e3b-9d6fc31f0c7e.png)
![Screenshot from 2021-01-13 15-22-42](https://user-images.githubusercontent.com/39888280/104406490-87c0d280-55b3-11eb-9383-9b62ec39917a.png)
![Screenshot from 2021-01-13 15-23-04](https://user-images.githubusercontent.com/39888280/104406491-88f1ff80-55b3-11eb-9f86-27585c9b2312.png)
![Screenshot from 2021-01-13 15-23-27](https://user-images.githubusercontent.com/39888280/104406503-90190d80-55b3-11eb-9d72-86da7005c1d1.png)
![Screenshot from 2021-01-13 15-23-41](https://user-images.githubusercontent.com/39888280/104406506-914a3a80-55b3-11eb-921b-6b11104791c2.png)

So to me it is not in that level of things.

None of them have anything like that command in there.

No offense:   Does your node have that command in there somewhere?   Just asking.

**Comment by drmibell** [comment]
Have you done the upgrade and refreshed your browser?

**Comment by Just-another-pleb** [comment]
No, at the same version as original.

Refreshed the browser?   The other machine did a reboot/reload of NR and so all things were wiped when NR came back up.

All data I give you is from a fresh loading of NR.

**Comment by drmibell** [comment]
Please use the **latest version**. As I said before, that will almost certainly eliminate the error message.

**Comment by Just-another-pleb** [comment]
Sorry, I thought I read "DON'T UPDATE".

Hang on.
(Went back and checked.  Sorry.  My bad.)

**Comment by Just-another-pleb** [comment]
Looking good!

Restarted NR and it came up no error.

Thanks.

So, again:  (just asking)   was that command used in your node somewhere?

**Comment by drmibell** [comment]
I don't know what you mean by a "command," but I think the answer is no. The error message you've been getting is produced by the JavaScript interpreter when it doesn't know what to do. The older versions of `q-gate` would throw an error for certain inputs that are now ignored. You probably should check to see that your flow behaves properly, since the node may be ignoring instead of acting on those inputs.

**Comment by Just-another-pleb** [comment]
msg.payload.toLowerCase

No problems.   It is now resolved.

Thanks.

**Comment by Just-another-pleb** [comment]
No problems.   

msg.payload.toLowerCase

It is not a command.   To me that's something of interest.   Only saying.
(Sorry for the big delay.   Thought I had sent this earlier.)
