### ISSUE TITLE
Just asking.

### ISSUE THREAD

**Issue by Just-another-pleb** [drmibell/node-red-contrib-queue-gate#20]
Can you set a queue size?
If that was possible from the node in the edit screen.

**Comment by Just-another-pleb** [comment]
Thanks.

(Alas I just shut that machine down)

I updated to the latest version and when I look on other machines I see that, but didn't on that (other) machine.

Sorry.   I'll have to check again next time I power it up.

**Comment by Just-another-pleb** [comment]
Ok, sorry.

I am missing something.

(asking for help to work out what)

This is what I see on the machine which prompted me to ask you:

![Screenshot from 2021-06-03 14-46-33](https://user-images.githubusercontent.com/39888280/120588455-8f0d4d80-c47a-11eb-9bdb-7be5edba1b53.png)
![Screenshot from 2021-06-03 14-46-46](https://user-images.githubusercontent.com/39888280/120588459-90d71100-c47a-11eb-842c-47ad82bf3b7b.png)

So:  it is up to date with version.

This is what I see on other machines which backs up what you say.
(Different theme)

![Screenshot from 2021-06-03 14-47-58](https://user-images.githubusercontent.com/39888280/120588557-bcf29200-c47a-11eb-98f3-8874b9eabc2b.png)
![Screenshot from 2021-06-03 14-48-04](https://user-images.githubusercontent.com/39888280/120588560-be23bf00-c47a-11eb-9b05-ffe718ef05e9.png)

I don't get what is happening.

No problem.   Not the end of the world.
But if you wouldn't mind explaining what is the cause....

I'd appreciate it.

**Comment by colinl** [comment]
The first one is a different node.  You must have installed another queue node as well as q-gate.

**Comment by Just-another-pleb** [comment]
Oh, I am sorry.

Really, really sorry.
