### ISSUE TITLE
Feature request: use an in-flight message counter limit, to automatically toggle between open and queue modes

### ISSUE THREAD

**Issue by shrickus** [drmibell/node-red-contrib-queue-gate#23]
I just recently discovered this exceptionally designed contrib node -- thanks for the nice docs and examples!

My current project involves using node-red flows to export millions of files out of a deprecated financial system, using rest APIs.  I started by using the `rate limit` node to limit the rest api calls (using `http request`) to 10/sec.  It works well for a while, but has no feedback mechanism to slow down the rate, if (and when) the server becomes overloaded.

Q-Gate to the rescue!  I can queue up 10's of thousands of requests, and use a "trigger" control msg to release the next request as soon as the previous one returns.  The only problem with this approach is that there is only 1 request in-flight at a time -- on a Tomcat server that can handle hundreds of simultaneous connections, this means the server is mostly idle.

Is there any way to set a "trigger limit" on the maximum number of in-flight msgs?  I'd like to be able to configure the q-gate to be initially "open", so any new messages pass right through, up to the point that say 10 msgs have been passed.  Once that limit is reached, the gate switches automatically to "queue" mode.  Every time a new "data" msg arrives it increments the in-flight counter, and every time a "control" message triggers the release of the oldest queued msg, the in-flight counter is decremented.  As long as the counter is below that limit, the mode is "open" -- at or above that limit the mode is "queue".

Would this be a worth-while enhancement request?  Or is there a better way to set a limit on the number of in-flight msgs?

**Comment by colinl** [comment]
You might be better to try node-red-contrib-semaphore for this. It can be configured to allow a defined number of messages through (the most common use is to allow only one, but you could configure it to allow hundreds if you want), then it will allow no more until a message passes through the semaphore release node.  So for each one out the end another one will be allowed in.

**Comment by drmibell** [comment]
Despite the kind words about `q-gate` (thanks), I have to agree with @colinl here. I have not used the `semaphore` node, but if works as advertised, it would be the better choice when starting from scratch. Still, if you want to modify your existing flow, it might not be difficult to add some logic downstream of the `q-gate` node to do the job. I would be happy to work with you on that.

There is one simple modification of the node that might add value here, if it passes review. That would be an option to have the `queueing` state switch automatically to `open` when the queue becomes empty. This would not completely eliminate the need for external logic in a use case like yours, but it would simplify it substantially. @colinl, do you see where this is coming from? Any thoughts?

**Comment by shrickus** [comment]
Wow, thanks guys - I've not used the `semaphore` nodes before, but you are correct that it is a better fit for this use case.
I do like that idea of automatically switching to `open` when the queue becomes "empty".

**Comment by colinl** [comment]
Just make sure that you get exactly one message out for every one in.  Think about whether there any situations where messages might get lost because of errors and you need to add a Catch node, for example.

**Comment by drmibell** [comment]
Good point. Unfortunately, there already are situations where messages are "lost." A number of commands will delete the queue when received in the `queueing` state. These include `reset`, `close`, and `default`. The `drop` command will also delete a message if there are any in the queue. I am working on enhancements (see PR #19) that would make it possible for the user to see the disposition of every message that arrives. So far, I have not found any error conditions that could cause message loss, with the possible exception of a read or write error to a context store, and this would be reported by the existing code. Of course, I'll go on looking for trouble...

**Comment by colinl** [comment]
Sorry, my comment was meant for @shrickus when using the semaphore nodes instead of the queue node.  You have to make sure that every message grabbing a semaphore must be matched with one releasing it at the end.

**Comment by drmibell** [comment]
Oops. Still something worth thinking about in the other context. Unless there's more to discuss, I'll close this issue.

**Comment by shrickus** [comment]
I took the semaphore node's advice and added a `catch` node to all the steps between the 'take' and 'leave' nodes.  It all works brilliantly, and we have managed to pull and save over 3,000 files per minute!  So, about 5x better than our initial tests with rate limiting at 10/sec...

Thanks again for the pointers, and the continual support you give to the node-red community.

**Comment by drmibell** [comment]
You're welcome. Credit goes to @colinl.
