### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Just-another-pleb** [drmibell/node-red-contrib-queue-gate#24]
If would be nice if the controlling *words* could be set from context/env variables.

It is just I am working on something and I have most of the problems worked around with other external nodes but am stuck with how to set the default state, which in my case would be a lot easier if I could use `env` variables.

**Comment by drmibell** [comment]
Any of the "controlling _words_" can be set to an environmental variable by entering something of the form ${ENV_VAR}. Since the default state is defined by a select box rather than a text field, I don't see any simple way to make that selection using an environmental variable.

**Comment by Just-another-pleb** [comment]
Oh, sorry.   Silly me.

Thanks.
