### ISSUE TITLE
Feature request - with queue size 1 have option to queue latest message rather than oldest

### ISSUE THREAD

**Issue by colinl** [drmibell/node-red-contrib-queue-gate#3]
It would be useful to be able to set the queue size to 1 but have it so that it is the latest message that is saved rather than the oldest. The result would be that the gate could be used to stop a stream of messages, possibly containing values of a slider for example, then when the gate is opened the latest value is released.

**Comment by colinl** [comment]
Looks good to me

**Comment by drmibell** [comment]
Thanks for the help. I will publish the new version shortly.

**Comment by drmibell** [comment]
Closing, since feature added in version 1.1.0.
