### ISSUE TITLE
Request: Provide queue state/number when new messages arrive

### ISSUE THREAD

**Issue by tsprivate** [drmibell/node-red-contrib-queue-gate#5]
Hi, you have a great node!

Is it possible to get the queue state (number of messages in queue) as output (maybe a 2nd output) whenever a new msg is arriving?  With this the subsequent node will be able to release next message whenever it has completed its task!

thanks for considering

**Comment by drmibell** [comment]
As it says in the README, when the node is in the `queueing` state, the status text displays `queueing: n`, where n is the number of messages in the queue. Whenever that number changes, an appropriately configured `status` node will receive a message. That message can be used, together with whatever additional logic you need, to trigger the `q-gate` to release the the next message. Unless I've missed something, this should give you all the tools you need.

**Comment by tsprivate** [comment]
Thanks for the quick response. Yes , a status node would solve it.

Could you provide a sample as I'm unaware of that feature.

Thanks for your help



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by tsprivate** [comment]
Ok , thanks for the advise .. I figured out the status node 👍👍



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by drmibell** [comment]
Brilliant! I was just about to post a flow for you to play with, but you will know what you need better than I can. I will close this issue, but feel free to ask more questions.
