### ISSUE TITLE
[Feature Request] Persistent queue

### ISSUE THREAD

**Issue by nirkons** [drmibell/node-red-contrib-queue-gate#6]
Hi,

It would be really amazing if there was an option to have the queue persistent (meaning it would survive even after a full deploy)

thanks!

**Comment by drmibell** [comment]
@nirkons this is very reasonable request. You may have noticed that the companion node [node-red-contrib-simple-gate ](https://github.com/drmibell/node-red-contrib-simple-gate)already has a `Restore from saved state` option, which can restore the open/closed state of the gate if the user has enabled a persistent form of storage. When I added this feature, I considered also adding it to the `q-gate` node, along with restoring the queue, but it was not clear how much demand there would be for it. A quick look at the code makes me think it would not be difficult to do, so I will try to get it working and documented in the next few days.

**Comment by colinl** [comment]
I too think this would be a useful extension.

**Comment by drmibell** [comment]
Sorry this has taken so long. I just pushed a branch called `persistence` that should add this feature. If you can, please give it a test drive. Remember, some kind of persistent storage has to be selected in the `settings.js` file. An easy way to test is to use the `Restart Flows` selection in the `Deploy` menu. This should force the context variables into persistent storage without having to wait for the `flushInterval` (30 seconds, by default). I would appreciate any feedback.

**Comment by drmibell** [comment]
I've had no feedback on this, but it seems to be working for me. I will merge the `persistence` branch into the master and publish it to npm shortly.
