### ISSUE TITLE
No way for other nodes to know how many are in queue?

### ISSUE THREAD

**Issue by Smith754** [drmibell/node-red-contrib-queue-gate#9]
I love this node, but it has no way of telling other nodes how many messages it is queuing when it is in queue mode.  I try to use an external counter node but invariably things get out of sync.  

It would be great if there was a second output on this node that just outputs how many messages are still in the queue.  That way, when something is added to the queue, the second output would spit out a number showing how many messages are in the queue waiting.

**Comment by colinl** [comment]
You can use a Status node monitoring the queue node.  Then the state and count is available in msg.status

**Comment by drmibell** [comment]
Thank you, Colin (@colinl). I somehow missed this issue. I think we can consider it resolved.
